/-
Authors: Achyuth Jayadevan
Released under CC0 1.0 Universal; see LICENSE.
-/
import Kourovka.Modules.ModuleRealization
import Mathlib.GroupTheory.HNNExtension

/-!
# Halfspace Splitting

The algebraic obstruction in the Bieri–Strebel two-halfspace argument.
Britton's lemma shows that twisting two elements outside the overlap produces
noncommuting images. This is used with a split Schreier presentation.
-/

namespace Kourovka.MetabelianEnumeration.HalfspaceSplitting

variable {N : Type*} [Group N]

abbrev Twist (C : Subgroup N) := HNNExtension N C C (MulEquiv.refl C)

def left (C : Subgroup N) : N →* Twist C := HNNExtension.of

def right (C : Subgroup N) : N →* Twist C :=
  ((MulAut.conj (HNNExtension.t⁻¹ : Twist C)).toMonoidHom).comp HNNExtension.of

theorem left_eq_right (C : Subgroup N) {c : N} (hc : c ∈ C) : left C c = right C c := by
  have h := HNNExtension.equiv_symm_eq_conj (φ := MulEquiv.refl C) (⟨c, hc⟩ : C)
  simpa [left, right, MulAut.conj_apply] using h

theorem not_commute_twist (C : Subgroup N) {a b : N} (ha : a ∉ C) (hb : b ∉ C) :
    ¬ Commute (left C a) (right C b) := by
  intro hab
  let w : HNNExtension.NormalWord.ReducedWord N C C :=
    { head := a
      toList := [(-1, b), (1, a⁻¹), (-1, b⁻¹), (1, 1)]
      chain := by simp [List.isChain_cons_cons, HNNExtension.toSubgroup, ha, hb] }
  have hw : w.prod (MulEquiv.refl C) = 1 := by
    have hcomm : left C a * right C b * (left C a)⁻¹ * (right C b)⁻¹ = 1 :=
      (commutatorElement_eq_one_iff_commute.mpr hab)
    simpa [w, HNNExtension.NormalWord.ReducedWord.prod, left, right, MulAut.conj_apply,
      mul_assoc] using hcomm
  have hn := HNNExtension.ReducedWord.toList_eq_nil_of_mem_of_range
    (MulEquiv.refl C) w (show w.prod (MulEquiv.refl C) ∈
      (HNNExtension.of.range : Subgroup (Twist C)) by rw [hw]; exact Subgroup.one_mem _)
  simp [w] at hn

/-- If an abelian group admits a homomorphism acting identically on one family
and by the stable-letter twist on another, one family lies in the overlap. -/
theorem abelian_twist_collapse (C A B : Subgroup N)
    (habelian : ∀ a b : N, Commute a b) (f : N →* Twist C)
    (hA : ∀ a ∈ A, f a = left C a) (hB : ∀ b ∈ B, f b = right C b) :
    A ≤ C ∨ B ≤ C := by
  by_contra! h
  obtain ⟨a, ha, hac⟩ := Set.not_subset.mp h.1
  obtain ⟨b, hb, hbc⟩ := Set.not_subset.mp h.2
  apply not_commute_twist C hac hbc
  simpa only [hA a ha, hB b hb] using (habelian a b).map f

/-- An abelian presentation whose defining words each use generators from just
one of two covering families is generated by one family alone. There is no
amalgam decomposition hypothesis: the twisting map is constructed from the
actual relators. -/
theorem abelian_presentation_one_side_generates {X : Type*}
    (R : Set (FreeGroup X)) (S T : Set X)
    (hcover : ∀ x, x ∈ S ∨ x ∈ T)
    (hrel : ∀ r ∈ R,
      r ∈ Subgroup.closure (FreeGroup.of '' S) ∨
      r ∈ Subgroup.closure (FreeGroup.of '' T))
    (habelian : ∀ a b : PresentedGroup R, Commute a b) :
    Subgroup.closure (PresentedGroup.of '' S : Set (PresentedGroup R)) = ⊤ ∨
    Subgroup.closure (PresentedGroup.of '' T : Set (PresentedGroup R)) = ⊤ := by
  classical
  let A : Subgroup (PresentedGroup R) := Subgroup.closure (PresentedGroup.of '' S)
  let B : Subgroup (PresentedGroup R) := Subgroup.closure (PresentedGroup.of '' T)
  let C := A ⊓ B
  let g : X → Twist C := fun x =>
    if x ∈ S then left C (PresentedGroup.of x) else right C (PresentedGroup.of x)
  have hgS : ∀ x ∈ S, g x = left C (PresentedGroup.of x) := by
    intro x hx; simp [g, hx]
  have hgT : ∀ x ∈ T, g x = right C (PresentedGroup.of x) := by
    intro x hx
    by_cases hs : x ∈ S
    · rw [hgS x hs]
      exact left_eq_right C ⟨Subgroup.subset_closure ⟨x, hs, rfl⟩,
        Subgroup.subset_closure ⟨x, hx, rfl⟩⟩
    · simp [g, hs]
  have hS : Set.EqOn (FreeGroup.lift g)
      ((left C).comp (PresentedGroup.mk R))
      (Subgroup.closure (FreeGroup.of '' S)) := by
    apply MonoidHom.eqOn_closure
    rintro _ ⟨x, hx, rfl⟩
    simpa only [FreeGroup.lift_apply_of, MonoidHom.comp_apply, PresentedGroup.of] using hgS x hx
  have hT : Set.EqOn (FreeGroup.lift g)
      ((right C).comp (PresentedGroup.mk R))
      (Subgroup.closure (FreeGroup.of '' T)) := by
    apply MonoidHom.eqOn_closure
    rintro _ ⟨x, hx, rfl⟩
    simpa only [FreeGroup.lift_apply_of, MonoidHom.comp_apply, PresentedGroup.of] using hgT x hx
  have hkill : ∀ r ∈ R, FreeGroup.lift g r = 1 := by
    intro r hr
    rcases hrel r hr with h | h
    · rw [hS h]
      simp only [MonoidHom.comp_apply, PresentedGroup.one_of_mem hr, map_one]
    · rw [hT h]
      simp only [MonoidHom.comp_apply, PresentedGroup.one_of_mem hr, map_one]
  let f : PresentedGroup R →* Twist C := PresentedGroup.toGroup hkill
  have hfS : Set.EqOn f (left C) A := by
    apply MonoidHom.eqOn_closure
    rintro _ ⟨x, hx, rfl⟩
    simpa only [f, PresentedGroup.toGroup.of] using hgS x hx
  have hfT : Set.EqOn f (right C) B := by
    apply MonoidHom.eqOn_closure
    rintro _ ⟨x, hx, rfl⟩
    simpa only [f, PresentedGroup.toGroup.of] using hgT x hx
  have hsup : A ⊔ B = ⊤ := by
    apply top_unique
    rw [← PresentedGroup.closure_range_of]
    apply (Subgroup.closure_le _).mpr
    rintro _ ⟨x, rfl⟩
    rcases hcover x with hx | hx
    · exact (le_sup_left : A ≤ A ⊔ B) (Subgroup.subset_closure ⟨x, hx, rfl⟩ : PresentedGroup.of x ∈ A)
    · exact (le_sup_right : B ≤ A ⊔ B) (Subgroup.subset_closure ⟨x, hx, rfl⟩ : PresentedGroup.of x ∈ B)
  rcases abelian_twist_collapse C A B habelian f (fun _ h => hfS h)
      (fun _ h => hfT h) with h | h
  · right
    have hab : A ≤ B := h.trans inf_le_right
    simpa only [sup_eq_right.mpr hab] using hsup
  · left
    have hba : B ≤ A := h.trans inf_le_left
    simpa only [sup_eq_left.mpr hba] using hsup

end Kourovka.MetabelianEnumeration.HalfspaceSplitting
