/-
Authors: Achyuth Jayadevan
Released under CC0 1.0 Universal; see LICENSE.
-/
import Kourovka.Halfspaces.SchreierPaths
import Kourovka.Halfspaces.HalfspaceLoops

/-!
# Halfspace Generation

Finite ordinary presentations force an abelian kernel to be generated by
loops in one of two valuation halfspaces.
-/

noncomputable section

namespace Kourovka.MetabelianEnumeration.SchreierHeights

open HalfspaceGeometry HalfspaceSplitting HalfspaceLoops
open Kourovka.Schreier.Discrete
open Kourovka.Schreier.Discrete.SchreierRewriting

variable {X L : Type} [AddCommGroup L] [DecidableEq X]

theorem transfer_generation {G H : Type*} [Group G] [Group H]
    (e : G ≃* H) (s : Set G) (t : Set H) (hs : Subgroup.closure s = ⊤)
    (ht : ∀ x ∈ s, e x ∈ t) : Subgroup.closure t = ⊤ := by
  have hmap : Subgroup.closure (e '' s) = ⊤ := by
    change Subgroup.closure (e.toMonoidHom '' s) = ⊤
    rw [← MonoidHom.map_closure e.toMonoidHom, hs,
      Subgroup.map_top_of_surjective e.toMonoidHom e.surjective]
  apply top_unique
  rw [← hmap]
  apply Subgroup.closure_mono
  rintro _ ⟨x, hx, rfl⟩
  exact ht x hx

theorem halfspace_generation_of_section (R : Set (FreeGroup X))
    (π : PresentedGroup R →* Multiplicative L) (χ : L →+ ℝ)
    (S : RightSchreierRepresentative (preKernel R π))
    (D B μ : ℝ) (hD0 : 0 ≤ D) (hDB : D ≤ B) (hμ : 2 * B ≤ μ)
    (hD : ∀ x, |value (χ.toMultiplicative.comp (π.comp (PresentedGroup.mk R)))
      (FreeGroup.of x)| ≤ D)
    (hR : ∀ r ∈ R, (r.toWord.length : ℝ) * D ≤ B)
    (hsafe : ∀ t : representativeSet S,
      PathIn (step (χ.toMultiplicative.comp (π.comp (PresentedGroup.mk R))))
        (fun z => min 0 (value (χ.toMultiplicative.comp (π.comp (PresentedGroup.mk R))) t.val) ≤ z ∧
          z ≤ max μ (value (χ.toMultiplicative.comp (π.comp (PresentedGroup.mk R))) t.val))
        0 t.val.toWord)
    (habelian : ∀ a b : π.ker, Commute a b) :
    Subgroup.closure (loopSet π χ PresentedGroup.of (fun z => 0 ≤ z)) = ⊤ ∨
      Subgroup.closure (loopSet π χ PresentedGroup.of (fun z => z ≤ μ)) = ⊤ := by
  let π₀ := π.comp (PresentedGroup.mk R)
  let θ := χ.toMultiplicative.comp π₀
  let e := schreierKernelEquiv R π S
  have hh (w : FreeGroup X) : value θ (S.representative w) = value θ w :=
    representative_height π₀ χ.toMultiplicative S w
  have hab : ∀ a b : PresentedGroup (representativeAugmentedPresentationRelators S R),
      Commute a b := by
    intro a b
    apply (commute_map_iff e.injective).mp
    exact habelian (e a) (e b)
  have hsplit := abelian_presentation_one_side_generates
    (representativeAugmentedPresentationRelators S R)
    (symbolsIn θ S (fun z => 0 ≤ z)) (symbolsIn θ S (fun z => z ≤ μ))
    (symbols_cover π₀ χ.toMultiplicative S D μ hD (by linarith))
    (augmented_relators_one_side π₀ χ.toMultiplicative S R D B μ hD0 hDB hμ hD hR hsafe) hab
  have htransfer (P : ℝ → Prop)
      (hP : ∀ t : representativeSet S, P (value θ t.val) →
        PathIn (step θ) P 0 t.val.toWord)
      (hgen : Subgroup.closure (PresentedGroup.of '' symbolsIn θ S P :
        Set (PresentedGroup (representativeAugmentedPresentationRelators S R))) = ⊤) :
      Subgroup.closure (loopSet π χ PresentedGroup.of P) = ⊤ := by
    apply transfer_generation e _ _ hgen
    rintro _ ⟨z, hz, rfl⟩
    have hz' : P (value θ z.1.val) ∧ P (value θ (z.1.val * FreeGroup.of z.2)) := hz
    refine ⟨generatorWord S z, ?_, ?_⟩
    · have heval (w : FreeGroup X) : FreeGroup.lift (PresentedGroup.of : X → PresentedGroup R) w =
          PresentedGroup.mk R w := (FreeGroup.lift_unique (PresentedGroup.mk R) (fun _ => rfl)).symm
      rw [heval, generatorWord_eval]
      exact (schreierKernelEquiv_of R π S z).symm
    · change PathIn (step θ) P 0 (generatorWord S z)
      apply generatorWord_path θ S hh P z hz (hP z.1 hz'.1)
      apply hP ⟨S.representative (z.1.val * FreeGroup.of z.2), ⟨_, rfl⟩⟩
      simpa only [hh] using hz'.2
  rcases hsplit with h | h
  · left
    apply htransfer (fun z => 0 ≤ z) _ h
    intro t ht
    apply (hsafe t).mono
    intro z hz
    have hzlo : min 0 (value θ t.val) ≤ z := hz.1
    simpa only [min_eq_left ht] using hzlo
  · right
    apply htransfer (fun z => z ≤ μ) _ h
    intro t ht
    apply (hsafe t).mono
    intro z hz
    have hzhi : z ≤ max μ (value θ t.val) := hz.2
    simpa only [max_eq_left ht] using hzhi

/-- Unconditional halfspace splitting for an actual finite ordinary
presentation with abelian kernel and abelian quotient. -/
theorem finite_presentation_halfspace_generation [Fintype X]
    (R : Set (FreeGroup X)) (hRfinite : R.Finite)
    (π : PresentedGroup R →* Multiplicative L) (hπ : Function.Surjective π)
    (χ : L →+ ℝ) (habelian : ∀ a b : π.ker, Commute a b) :
    ∃ μ : ℝ, 0 ≤ μ ∧
      (Subgroup.closure (loopSet π χ PresentedGroup.of (fun z => 0 ≤ z)) = ⊤ ∨
        Subgroup.closure (loopSet π χ PresentedGroup.of (fun z => z ≤ μ)) = ⊤) := by
  classical
  let π₀ := π.comp (PresentedGroup.mk R)
  let θ := χ.toMultiplicative.comp π₀
  let D : ℝ := 1 + ∑ x : X, |value θ (FreeGroup.of x)|
  have hD0 : 0 ≤ D := by dsimp [D]; positivity
  have hD : ∀ x, |value θ (FreeGroup.of x)| ≤ D := by
    intro x
    have hh := Finset.single_le_sum (fun y _ => abs_nonneg (value θ (FreeGroup.of y)))
      (Finset.mem_univ x)
    dsimp [D]
    linarith
  let B := D + ∑ r ∈ hRfinite.toFinset, (r.toWord.length : ℝ) * D
  have hDB : D ≤ B := by
    dsimp [B]
    exact le_add_of_nonneg_right (Finset.sum_nonneg fun r _ => mul_nonneg (Nat.cast_nonneg _) hD0)
  have hR : ∀ r ∈ R, (r.toWord.length : ℝ) * D ≤ B := by
    intro r hr
    have hh := Finset.single_le_sum (fun w _ => mul_nonneg (Nat.cast_nonneg w.toWord.length) hD0)
      (hRfinite.mem_toFinset.mpr hr)
    dsimp [B]
    linarith
  let μ := 2 * B
  obtain ⟨r, hr, h1, hp⟩ := exists_safe_section π₀
    (hπ.comp (PresentedGroup.mk_surjective R)) χ.toMultiplicative D μ hD0 hD (by dsimp [μ]; linarith)
  let S := representativeOfSection π₀ r hr h1
  have hsafe : ∀ t : representativeSet S,
      PathIn (step θ) (fun z => min 0 (value θ t.val) ≤ z ∧ z ≤ max μ (value θ t.val))
        0 t.val.toWord := by
    rintro ⟨_, ⟨w, rfl⟩⟩
    simpa only [S, representativeOfSection, step, θ, value, MonoidHom.comp_apply, hr] using hp (π₀ w)
  refine ⟨μ, by dsimp [μ]; linarith, ?_⟩
  exact halfspace_generation_of_section R π χ S D B μ hD0 hDB le_rfl hD hR hsafe habelian

end Kourovka.MetabelianEnumeration.SchreierHeights
