/-
Authors: Achyuth Jayadevan
Released under CC0 1.0 Universal; see LICENSE.
-/
import Kourovka.Halfspaces.HalfspaceModule
import Kourovka.Modules.LaurentAction
import Kourovka.Halfspaces.HalfspaceGeometry

/-!
# Halfspace Loops

The module generated by loops in a valuation halfspace.
-/

noncomputable section

namespace Kourovka.MetabelianEnumeration.HalfspaceLoops

open HalfspaceGeometry HalfspaceModule ValuationModule

variable {E L X : Type} [Group E] [AddCommGroup L]

/-- Actual kernel elements represented by words whose successive vertices
stay in the specified height region. -/
def loopSet (π : E →* Multiplicative L) (χ : L →+ ℝ) (g : X → E)
    (P : ℝ → Prop) : Set π.ker :=
  {n | ∃ w : List (X × Bool), FreeGroup.lift g (FreeGroup.mk w) = n.val ∧
    PathIn (letterHeight (fun x => χ (π (g x)).toAdd)) P 0 w}

end Kourovka.MetabelianEnumeration.HalfspaceLoops
